### ISSUE TITLE
FCOM Client crash problem

### ISSUE THREAD

**Issue by sparrowhe** [norrisng/FcomClient#14]
```
2023-06-08 04:20:58Z: [CRASH] SharpPcap.PcapException: Unable to open the adapter (rpcap://\Device\NPF_{9F062D47-930C-4BC3-9361-74F82F25D344}). Error opening adapter: 文件名、目录名或卷标语法不正确（this is a error message in Chinese system, Google translate: Incorrect filename, directory name, or volume label syntax）。  (123)
   SharpPcap.LibPcap.LibPcapLiveDevice.Open(DeviceMode mode, Int32 read_timeout, MonitorMode monitor_mode)
   SharpPcap.LibPcap.LibPcapLiveDevice.Open(DeviceMode mode, Int32 read_timeout)
   FcomClient.UI.FcomClient.Main(String[] args)
```

I confirm that I have installed winpcap, and I am using the newest FCOM client

**Comment by xfoxfu** [comment]
I am having a similar problem on Windows 11 with Npcap 1.77.

```console
2023-10-20 06:57:20Z: [CRASH] SharpPcap.PcapException: Unable to open the adapter (rpcap://\Device\NPF_{****************}). Error opening adapter: The filename, directory name, or volume label syntax is incorrect.  (123)
   at SharpPcap.LibPcap.LibPcapLiveDevice.Open(DeviceMode mode, Int32 read_timeout, MonitorMode monitor_mode)
   at SharpPcap.LibPcap.LibPcapLiveDevice.Open(DeviceMode mode, Int32 read_timeout)
   at FcomClient.UI.FcomClient.Main(String[] args)
```

I have refactored the code to use SharpPcap 6.2.5 and things just worked. I think the problem is related to a too old version of SharpPcap.
